### ISSUE TITLE
Running ROS2 demo nodes with CycloneDDS and FastRTPS

### ISSUE THREAD

**Issue by omertal88** [eclipse-cyclonedds/cyclonedds#1110] opened 2022-01-18 11:51 UTC
Hello,

I recently came across an issue when tring to run the demo nodes with a combination of both DDS providers.
I tried to run the ROS2 _talker_ node with FastRTPS, and _listener_ node with CycloneDDS.

When I run the talker node first, everything works fine. But when I run the listener node first I am missing the first 4 messages...

I am running on Ubuntu 20.04 with ros2-galactic.

Talker:
```
$ RMW_IMPLEMENTATION=rmw_fastrtps_cpp ros2 run demo_nodes_cpp talker
[INFO] [1642506340.699794564] [talker]: Publishing: 'Hello World: 1'
[INFO] [1642506341.699780112] [talker]: Publishing: 'Hello World: 2'
[INFO] [1642506342.699645135] [talker]: Publishing: 'Hello World: 3'
[INFO] [1642506343.699805486] [talker]: Publishing: 'Hello World: 4'
[INFO] [1642506344.699794865] [talker]: Publishing: 'Hello World: 5'
[INFO] [1642506345.699628593] [talker]: Publishing: 'Hello World: 6'
[INFO] [1642506346.699735169] [talker]: Publishing: 'Hello World: 7'
[INFO] [1642506347.699833032] [talker]: Publishing: 'Hello World: 8'
```
Listener:
```
$ RMW_IMPLEMENTATION=rmw_cyclonedds_cpp ros2 run demo_nodes_cpp listener
[INFO] [1642506344.700722927] [listener]: I heard: [Hello World: 5]
[INFO] [1642506345.699918529] [listener]: I heard: [Hello World: 6]
[INFO] [1642506346.700476426] [listener]: I heard: [Hello World: 7]
[INFO] [1642506347.700750938] [listener]: I heard: [Hello World: 8]
```
I'm not sure if that's an issue with cyclonedds of fastrtps. I should mention that I've done this test in order to investigate different discovery issues I have between cyclonedds and fastrtps.
 
I configured cyclonedds verbosity to finest and attached the log here for debugging purposes.

Thank you
Omer

[cyclonedds_output.txt](https://github.com/eclipse-cyclonedds/cyclonedds/files/7888782/cyclonedds_output.txt)

**Comment by eboasson** [comment] 2022-01-18 21:29
@omertal88 it does receive the preceding samples, but it discards them because it hasn't yet received a "heartbeat" message from the FastRTPS writer. The "heartbeat" message informs the readers of the sequence numbers currently available (if you search for occurrences of the writer's GUID `10fd2a8:b92358a6:1000000:1203` you'll see "no heartbeat seen yet" for the first `DATA` messages). That means it hasn't yet been able to complete the handshake necessary to guarantee precise (and I would say "correct") behaviour of volatile readers and can't deliver the data yet (I believe Cyclone is the only implementation that is very strict about this). If you're curious why it won't deliver data it receives, there are some comments of mine on older issues that try to describe in detail the need for that handshake in more detail (I think #337 or #165, there may be others as well).

All that happens is entirely in accordance with the spec. The timing of those "heartbeats" is left open and so neither implementation is wrong and it isn't strictly speaking a bug. However, since Cyclone implements a protocol feature for trying to make the writer send them, I want to look a bit further into this to see why that it takes so long for a "heartbeat" to come through. Perhaps there's an easy way to change this because I do agree that 5s is a bit much!

**Comment by eboasson** [comment] 2022-01-19 13:39
I had another look and additionally managed to reproduce it. Cyclone is doing all I expect it to do, and I believe it is FastRTPS that is not playing along as it should in its handling of the messages that make up the reliable protocol.

The bonus: I did find Cyclone is missing a specific event in its tracing, but that of course does not affect the behaviour.

Closing this issue because it is not my task to root cause deficiencies in other implementations.

**Closed by eboasson** 2022-01-19 13:39 UTC
