### ISSUE TITLE
About DDS-XTypes standard and C++

### ISSUE THREAD

**Issue by i-and** [eclipse-cyclonedds/cyclonedds#53] opened 2018-11-21 16:36 UTC
Do you plan to implement the DDS-XTypes standard?
Do you plan to implement the C++ interface?

**Comment by k0ekk0ek** [comment] 2018-11-21 16:58
Hi @i-and. Yes, both are being worked on. The C++ interface is actually already (mostly) done, but we can't generate type support yet for Cyclone using the open source IDL compiler. That part is currently being worked on here https://github.com/FransFaase/cyclonedds in the form of a new IDL compiler. The new compiler is also a big part of the puzzle for DDS-XTypes.

**Comment by i-and** [comment] 2019-04-20 21:26
Hi @eboasson.
Can you open your plans and specify when the following will be implemented in the CycloneDDS: 
1. IDL generator and Cyclone serializer support for data type evolution with extensibility=mutable| append|final, id, optional, mustUnderstand, tryConstruct;
2. support all items from the TypeSystem? (I haven't found Union and enum yet);
3. discovery-Time Data Typing (the dynamic features of DDS-XTypes depend on the ability of components to discover the data types used by their peers);
4. Type Consistency Enforcement at Discovery-Time;
5. Dynamic Language Binding API - constructing new types as well as introspecting existing types.
Is it possible to implement the first two points in 2019?

**Comment by eboasson** [comment] 2019-04-23 19:34
Hi @i-and,

XTypes — you basically list all of it 😄 — doesn't figure very prominently in my plans. I do see that many people using DDS want to use it, but as the only thing I control is some of my own time, I have to make choices. I personally am more interested in trying to make dynamic memory allocation optional (quite a challenge) and improving Cyclone's behaviour in more complex networks. I'm very interested in seeing DDS Security added, even if l hope I can escape doing it myself. Full support for ROS2 is higher on my list than XTypes. (At the same time, as I am really interested in seeing more people use Cyclone, if the application you're thinking of is interesting to me, it might affect its position in my personal wish list.)

That doesn't mean I wouldn't be very happy to take contributions to add XTypes support. I am really simply hoping someone will step up and start the work in earnest. The progress so far by those in Adlink who indicated they'd work on it has been limited so far, sadly, but that can still change.

I do believe that anyone with some affinity with the matter can do it and that we could integrate it in Cyclone as it develops. If someone puts the effort in, I'd say for sure it can be done this year.

The reason for my belief is that XTypes is mostly a number pretty standard things: IDL, type representations, serialisation, language mapping, … It is perhaps time-consuming because of the sheer size of the spec, and perhaps in part also when one considers the conditions under which it is to operate (real-time, embedded platforms), but it is not so because of requiring innovative steps:
* IDL preprocessing and conversion into an internal representation that is suitable for checking compatibility, generating code, &c., is pretty standard compiler technology (mostly without the need for interesting optimisations);
* serialisation of the various forms is pretty well spec'd out and building a compliant implementation is therefore mostly a matter of doing the work;
* type descriptor representation is also spec'd (IIRC) by defining the elements of a type definition in IDL, so the descriptor is the result of serialising the definition with the same serialiser;
* type consistency checking/enforcement can very sensible be done at the point where RxO matching also takes place: at this point all relevant data is available;
* the dynamic interfaces are largish but build on the same type metadata that needs to be exchanged and generated by the IDL preprocessor, so these will take time but should not at all be difficult to do.

Therefore the real question for anyone contemplating this work is whether it would be hard to integrate this in Cyclone. In my opinion, it isn't: there is no need to fit it into the format currently used for (de)serialisation, nor to extend the current (so-so) IDL preprocessor code (I prefer a new one, not written in Java as a matter of fact). It is one of the reasons behind my putting in a more abstract notion of types and samples: to make it possible to have different serialisation routines with minimal dependencies on the internals of Cyclone.

That means (or should mean) one can have a mostly self-contained code base handling IDL preprocessing, type description, serialiser, copy to/from application code, … There'll be some work needed to add the metadata to the discovery and to add a call the correct routine for checking type compatibility during reader/writer matching, but the integration effort really ought to be pretty small.

This being possible doesn't mean I'd like to keep an XTypes implementation at a distance forever. For one thing, I'd much prefer to use the same serialiser for application mutable types and the discovery data. But having the option of implementing it with just some minor changes in Cyclone means that it is something that can be done independently by someone not deeply familiar with the current internals.

**Comment by i-and** [comment] 2019-04-23 23:01
Hi, @eboasson,

>At the same time, as I am really interested in seeing more people use Cyclone, if the application you're thinking of is interesting to me, it might affect its position in my personal wish list.

As I see it - an interesting application is a kind of built-in system consisting of several dozen computers. At the same time, each computer has its own SOFTWARE and its developer. How can you organize a DDS data model without X-Types to ensure the development of the system (change/add/remove data) during its debugging and life cycle? Restriction - one-time transition to the new version of SOFTWARE/topics for all participating computers - is impossible. 
To generate for each data new topic, probably redundant and inefficient? What are the possible options for current Cyclone DDS? 
By the way, I conducted an experiment with the bandwidth test. Changed the IDL description:
~~~
  struct DataType
  {
    long k;
    unsigned long long count;
    sequence<octet> payload;
  };
  #pragma keylist DataType
~~~
and rebuilt only publisher - subscriber remained on IDL without the element "long k;". As a result, I expected some kind of error related to the incompatibility of topic types. But in reality it turned out that: subscriber several seconds accepts topics with **random** size after which the application ends with an exception. Can you comment on this?

**Comment by eboasson** [comment] 2019-04-24 12:26
> As I see it - an interesting application is a kind of built-in system consisting of several dozen computers. At the same time, each computer has its own SOFTWARE and its developer. How can you organize a DDS data model without X-Types to ensure the development of the system (change/add/remove data) during its debugging and life cycle? Restriction - one-time transition to the new version of SOFTWARE/topics for all participating computers - is impossible.

But also: how do you ensure that the independently made changes are compatible? And it is easy to say there should be no communication between a reader and a writer if (in XTypes terminology) the reader's type is not assignable from the writer's type, but that approach brings huge problems when one considers transient data.

From what I've seen over the years, extending the data model is by far the most common change. Given that, the more natural model of evolving a data type in the underlying programming model of DDS — or more precisely: of DDS when used as a shared data space — is to extend the data model by adding topics. I find that a more elegant approach, but it does come with a cost: for that model to work, DDS _must_ be improved to make what the spec calls "multi topics" very easy to use.

For the more message-oriented applications, evolving types like XTypes, makes relatively more sense. For those cases, "multi topics" are very unnatural, and as those systems tend to avoid transient data, the trouble with inconsistent definitions and transient data doesn't really exist.

XTypes is one particular point in a spectrum of solutions for the same problem, but by no means the only one. Its major distinction is that it is standardized within the DDS family of specifications. That's enough to say that from a practical point of view, there's no question that XTypes support in Cyclone is desirable.

> To generate for each data new topic, probably redundant and inefficient? 

A separate topic for each variant will probably drive you mad if you then have to handle very many versions ...

> What are the possible options for current Cyclone DDS?

Today, the quickest route is to use something like Google protobuf, flatbuffers, JSON/BSON data, or … (it ties in with your question #162, I figure). One can integrate these quite nicely, for example OpenSplice has google protobuf integrated in the C++ API, so that you simply read/write GPB data.

> As a result, I expected some kind of error related to the incompatibility of topic types. But in reality it turned out that: subscriber several seconds accepts topics with random size after which the application ends with an exception. Can you comment on this?

I'm not surprised: that's the pre-XTypes DDS biting you. That said ... it had slipped my mind that one of the benefits of implementing XTypes (even if only partially) is that without it, these checks are missing.

Several implementations used to use vendor-specific extensions to enable type checking, but obviously it now makes no sense to do it in a vendor-specific way, it makes far more sense to implement it as specified in the XTypes standard.

**Comment by hansvanthag** [comment] 2019-04-24 12:49
small note: GPB support in OpenSplice is for both C++ as well as Java :)

**Comment by i-and** [comment] 2019-04-24 20:52
>But also: how do you ensure that the independently made changes are compatible?

Let me clarify that of course all developers should have the same basic representation of topics with mandatory fields. Here, independence refers to the process of recompiling and updating SOFTWARE developed on one basic, but evaluative model.

> Today, the quickest route is to use something like Google protobuf, flatbuffers, JSON/BSON data, or … (it ties in with your question #162, I figure).

You got that right, my question #162 was related to the fact, to use an alternative serialization algorithm that support the evolution of types, until the realization of XTypes in the Cyclone. With this approach, there are also disadvantages due to the fact that the models from proto-files and IDL have some semantic differences and the conversion between them can lead to a change in functioning already running systems (if consider the GPB as a temporary solution).

I hope that as a result of this discussion (and given the practical experiment with incompatible topics), the big task of implementing XTypes in your todo list has risen higher.

**Comment by i-and** [comment] 2019-05-07 19:05
> It nudged it up a notch :smile:

:+1: 

@eboasson, please answer the following:
1. https://github.com/eclipse-cyclonedds/cyclonedds/issues/53#issuecomment-486005070
> and rebuilt only publisher - subscriber remained on IDL without the element "long k;". As a result, I expected some kind of error related to the incompatibility of topic types. But in reality it turned out that: subscriber several seconds accepts topics with random size after which the application ends with an exception.

This behavior is similar to going beyond the received message (presumably because the size of the received array contains uninitialized - random data - the new "long k;"field). Is it possible to implement the discarding of received samples (with an alarm about this fact), if in the process of their decoding there is a lack of data? This should increase the reliability of the reception of inconsistent topics.

2. Can we say that in the current implementation of the Cyclone implemented the evolution of the types of topics of the form "extensibility=append"?. I. e. is it possible to add new fields to the end of the type while old clients should accept new topics, ignoring new fields?

**Comment by eboasson** [comment] 2019-05-08 01:42
> This behavior is similar to going beyond the received message (presumably because the size of the received array contains uninitialized - random data - the new "long k;"field). Is it possible to implement the discarding of received samples (with an alarm about this fact), if in the process of their decoding there is a lack of data? This should increase the reliability of the reception of inconsistent topics.

Yes, definitely. Not doing that is a major bug. A quick check of the source suggests it does check this if assertions are enabled, so I'll privately wonder who made that choice and why, probably without ever learning the answer ... Suffice it to say this will be addressed with priority.

> Can we say that in the current implementation of the Cyclone implemented the evolution of the types of topics of the form "extensibility=append"?. I. e. is it possible to add new fields to the end of the type while old clients should accept new topics, ignoring new fields?

Yes, you can mostly treat it like that. There is a catch: in the original specs the exact length of the payload is not given. It simply runs until the next submessage/end of the message and the CDR requirement that messages be aligned to 4 byte boundaries introduces some ambiguity. That never was an issue until XTypes, and got fixed by using two bits of the (previously, required to be 0) "options" field in the encoding information to indicate how many padding bytes there are.

So with just the fix for reading beyond the buffer it will mostly work as-if appendable, but there are some corner cases, such as extending ``struct { octet a; }`` to struct ``{ octet a; octet b; }`` that will behave differently as they'd both occupy four bytes. Implementing the additional XTypes rules with respect to those two bits in the "options" field and clearing the padding as required by it would make it work as you describe. I'll have to double check a few things but I expect no problem in also doing that little bit.

Note that it would technically make the extensibility setting "extensible", not "appendable". "Extensible" is deprecated and replaced by "appendable" in the spec to deal with extending inner struct types. Suppose you'd have a reader with this model:
```IDL
@extensibility(APPENDABLE)
struct S {
  long a;
}
@extensibility(APPENDABLE)
struct T {
  S x;
  long y;
}
```
and a writer with:
```IDL
@extensibility(APPENDABLE)
struct S1 : S {
  long b;
}
@extensibility(APPENDABLE)
struct T {
  S1 x;
  long y;
}
```
With the traditional CDR encoding (used by "extensible" mode) the reader would mistakenly set the value of "y" to that written by the writer as "x.b" in the old scheme. "Appendable" uses a different encoding that takes care of that by adding additional length information. So ... if you play with it, just make sure to avoid extending nested structs.

**Comment by i-and** [comment] 2019-05-10 19:28
>So with just the fix for reading beyond the buffer it will mostly work as-if appendable, but there are some corner cases, such as extending struct { octet a; } to struct { octet a; octet b; } that will behave differently as they'd both occupy four bytes. Implementing the additional XTypes rules with respect to those two bits in the "options" field and clearing the padding as required by it would make it work as you describe. I'll have to double check a few things but I expect no problem in also doing that little bit.

As far as I understand correctly, the situation with padding will be relevant when writer writes the old "short" topic, and reader takes a new "long topic". It really is also important to accurately check whether the decoding of the boundaries of the submessage.
What is the behavior when receiving the "short" topic you realize at this stage: 
1. Simple but with limiting interoperability - the received topic is discarded. 
2. According to XTypes (if I understood it correctly) - the default value is set according to table 9 - Default values for non-optional members.

By the way, can you clarify the provisions of the standard: what keywords are used to explicitly set the default value for the fields of structures/unions?

> With the traditional CDR encoding (used by "extensible" mode) the reader would mistakenly set the value of "y" to that written by the writer as "x.b" in the old scheme. "Appendable" uses a different encoding that takes care of that by adding additional length information. So ... if you play with it, just make sure to avoid extending nested structs.

To avoid errors due to the mismatch between Topics, suggests the decision not to use nested structures and sequence  of structures at all (that would not like). As an alternative - support in Cyclone DELIMITED_CDR encoding. But it will have to fully support the @extensibility(APPENDABLE) annotation... What do you think about this?

**Comment by eboasson** [comment] 2019-05-13 14:28
> As far as I understand correctly, the situation with padding will be relevant when writer writes the old "short" topic, and reader takes a new "long topic". It really is also important to accurately check whether the decoding of the boundaries of the submessage.

Correct — so I'm not taking any chances: I've reverse-engineered the existing mechanism, fixed some inconsistencies & updated it to fix most of its problems. (Not yet the padding issue at the end, but that should now be straightforward as well). Next is giving it a decent workout to have some confidence that it really works. (Within the limitations of the types the current preprocessor can handle: there's some progress again on the preprocessing and XTypes front: see #180.)

> What is the behavior when receiving the "short" topic you realize at this stage:
>
> Simple but with limiting interoperability - the received topic is discarded.

For now, yes. I have considered what I could do about defaulting missing fields, and I might at some point make it possible have the tail of a top-level struct zero'd out, but that's about how far I can go without actually implementing all of XTypes. (And mostly compatible with XTypes, of course.)

>According to XTypes (if I understood it correctly) - the default value is set according to table 9 - Default values for non-optional members.
> By the way, can you clarify the provisions of the standard: what keywords are used to explicitly set the default value for the fields of structures/unions?

I'm not entirely sure: looking through the spec again, I'd almost say it is not supported, except for unions (the ``@default_literal`` annotation; section 7.3.1.2.1.10).

> To avoid errors due to the mismatch between Topics, suggests the decision not to use nested structures and sequence of structures at all (that would not like). As an alternative - support in Cyclone DELIMITED_CDR encoding. But it will have to fully support the @extensibility(APPENDABLE) annotation... What do you think about this?

That will come with XTypes support — it's not that the encoding bit would be hard to do, the problem is that the current preprocessor erases some of the structure when it generates instruction for a small serializer VM (the implementation of which I'm fixing). With a new preprocessor on its way I'm hoping not to have to do anything on the old one ...

**Comment by i-and** [comment] 2019-05-13 20:08
> I've reverse-engineered the existing mechanism, fixed some inconsistencies & updated it to fix most of its problems. (Not yet the padding issue at the end, but that should now be straightforward as well).

Clarify, in this regard, whether there will be a new commit that eliminates the problem of reading outside the message in the process of decoding?

> I'm not entirely sure: looking through the spec again, I'd almost say it is not supported, except for unions (the @default_literal annotation; section 7.3.1.2.1.10).

A small clarification 7.3.1.2.1.10 - the "Default Literal for Enumeration" is not for unions. Apparently in XTypes specifying an explicit default value for a aggregated types (structs, unions) is currently impossible. For example, in GPB this is done as follows: 
~~~
optional string path = 1 [default = "/"];
optional bool path_error = 1 [default = false];
~~~

**Comment by eboasson** [comment] 2019-05-14 14:24
> Clarify, in this regard, whether there will be a new commit that eliminates the problem of reading outside the message in the process of decoding?

I considered that to be self-evident!

>> I'm not entirely sure: looking through the spec again, I'd almost say it is not supported, except for unions (the @default_literal annotation; section 7.3.1.2.1.10).
> A small clarification 7.3.1.2.1.10 - the "Default Literal for Enumeration" is not for unions. Apparently in XTypes specifying an explicit default value for a aggregated types (structs, unions) is currently impossible. For example, in GPB this is done as follows:

I see I made a typo: I meant to write "enum" not "union". Apologies for the confusion and thanks for clearing it up.

**Comment by thijsmie** [comment] 2022-06-15 10:43
There is a lot of knowledge and discussion on this ticket, but the core part "Do we have C++" and "Do we have XTypes" the answer is a resounding "Yes!" and therefore I am closing this and relegating it to the knowledge-base.

**Closed by thijsmie** 2022-06-15 10:43 UTC
Labels: knowledge-base
