### ISSUE TITLE
Failing to compile large IDL structures since #1077 merged

### ISSUE THREAD

**Issue by clalancette** [eclipse-cyclonedds/cyclonedds#1104] opened 2022-01-11 14:08 UTC
We have some performance tests on the ROS 2 buildfarm that generate fairly large structures.  Up until https://github.com/eclipse-cyclonedds/cyclonedds/pull/1077, this would actually compile (and work, at least for some definition of work) on the buildfarm.  Once 1077 was applied, though, we are seeing failures to build on the buildfarm, like https://build.ros2.org/view/Rci/job/Rci__nightly-performance_ubuntu_focal_amd64/485/console .

The problem can be pretty easily reproduced trying to run `idlc` against the following IDL file:

```
#ifndef __performance_test_msgs__msg__Struct32k__idl__
#define __performance_test_msgs__msg__Struct32k__idl__

module performance_test_msgs
{

module msg
{

module dds_
{

struct Struct16_
{

  octet struct0_;
  octet struct1_;
  octet struct2_;
  octet struct3_;
  octet struct4_;
  octet struct5_;
  octet struct6_;
  octet struct7_;
  octet struct8_;
  octet struct9_;
  octet structa_;
  octet structb_;
  octet structc_;
  octet structd_;
  octet structe_;
  octet structf_;
  long long time_;
  unsigned long long id_;

};  // struct Struct16_

struct Struct256_
{

  performance_test_msgs::msg::dds_::Struct16_ struct160_;
  performance_test_msgs::msg::dds_::Struct16_ struct161_;
  performance_test_msgs::msg::dds_::Struct16_ struct162_;
  performance_test_msgs::msg::dds_::Struct16_ struct163_;
  performance_test_msgs::msg::dds_::Struct16_ struct164_;
  performance_test_msgs::msg::dds_::Struct16_ struct165_;
  performance_test_msgs::msg::dds_::Struct16_ struct166_;
  performance_test_msgs::msg::dds_::Struct16_ struct167_;
  performance_test_msgs::msg::dds_::Struct16_ struct168_;
  performance_test_msgs::msg::dds_::Struct16_ struct169_;
  performance_test_msgs::msg::dds_::Struct16_ struct16a_;
  performance_test_msgs::msg::dds_::Struct16_ struct16b_;
  performance_test_msgs::msg::dds_::Struct16_ struct16c_;
  performance_test_msgs::msg::dds_::Struct16_ struct16d_;
  performance_test_msgs::msg::dds_::Struct16_ struct16e_;
  performance_test_msgs::msg::dds_::Struct16_ struct16f_;
  long long time_;
  unsigned long long id_;

};  // struct Struct256_

struct Struct4k_
{

  performance_test_msgs::msg::dds_::Struct256_ struct2560_;
  performance_test_msgs::msg::dds_::Struct256_ struct2561_;
  performance_test_msgs::msg::dds_::Struct256_ struct2562_;
  performance_test_msgs::msg::dds_::Struct256_ struct2563_;
  performance_test_msgs::msg::dds_::Struct256_ struct2564_;
  performance_test_msgs::msg::dds_::Struct256_ struct2565_;
  performance_test_msgs::msg::dds_::Struct256_ struct2566_;
  performance_test_msgs::msg::dds_::Struct256_ struct2567_;
  performance_test_msgs::msg::dds_::Struct256_ struct2568_;
  performance_test_msgs::msg::dds_::Struct256_ struct2569_;
  performance_test_msgs::msg::dds_::Struct256_ struct256a_;
  performance_test_msgs::msg::dds_::Struct256_ struct256b_;
  performance_test_msgs::msg::dds_::Struct256_ struct256c_;
  performance_test_msgs::msg::dds_::Struct256_ struct256d_;
  performance_test_msgs::msg::dds_::Struct256_ struct256e_;
  performance_test_msgs::msg::dds_::Struct256_ struct256f_;
  long long time_;
  unsigned long long id_;

};  // struct Struct4k_

struct Struct32k_
{

  performance_test_msgs::msg::dds_::Struct4k_ struct4k0_;
  performance_test_msgs::msg::dds_::Struct4k_ struct4k1_;
  performance_test_msgs::msg::dds_::Struct4k_ struct4k2_;
  performance_test_msgs::msg::dds_::Struct4k_ struct4k3_;
  performance_test_msgs::msg::dds_::Struct4k_ struct4k4_;
  performance_test_msgs::msg::dds_::Struct4k_ struct4k5_;
  performance_test_msgs::msg::dds_::Struct4k_ struct4k6_;
  performance_test_msgs::msg::dds_::Struct4k_ struct4k7_;
  long long time_;
  unsigned long long id_;

};  // struct Struct32k_


};  // module dds_

};  // module msg

};  // module performance_test_msgs

#endif  // __performance_test_msgs__msg__Struct32k__idl__
#pragma keylist performance_test_msgs::msg::dds_::Struct32k_
```

Interestingly, if I comment out either the `structk4k7_` line, *or* the `#pragma keylist performance_test_msgs::msg::dds_::Struct32k_` line, things succeed.

I'm not quite sure how to proceed here; it's not clear to me if this is a bug in CycloneDDS, or if we just need to make our structures simpler.  Any advice here would be appreciated @dennis-adlink @eboasson .

**Comment by dennis-adlink** [comment] 2022-01-12 09:37
The error message from the build log `Maximum number of instructions (65500) reached. Failed to compile '/tmp/ws2/build_isolated/performance_test/src/idlgen/cyclonedds/gen/cyclonedds/Struct32k_.idl`, is introduced in #1077. As explained in https://github.com/eclipse-cyclonedds/cyclonedds/issues/1060#issuecomment-986208701, the large number of serializer instructions is caused by writing out all members explicitly. Before #1077 the IDL compiler ignored this issue, which caused the build to succeed but resulted in incorrect serializer instruction in the topic descriptor (and that would result in failing tests). 

In PR #903 (in Cyclone master branch) re-using types in the serializer instructions is implemented, but that change can't be easily backported to 0.8. @eboasson's comment on #1060 suggests some changes in the structures to make it work with the 0.8 IDL compiler. As ROS/RMW is not using Cyclone's IDL compiler, this would only be useful if the performance tests are running for native-Cyclone, which I think is not the case on the ROS build farm? (these tests would also have failed before #1077) So you could also consider disabling building the performance tests for native Cyclone on ROS CI as a fix for this issue.

**Comment by clalancette** [comment] 2022-01-12 14:42
Thanks for the feedback.

> As ROS/RMW is not using Cyclone's IDL compiler, this would only be useful if the performance tests are running for native-Cyclone, which I think is not the case on the ROS build farm? (these tests would also have failed before #1077) So you could also consider disabling building the performance tests for native Cyclone on ROS CI as a fix for this issue.

Right, for ROS 2 itself, we do not use `idlc` (I believe).  However, the https://github.com/ros2/performance_test repository tests both native code and ROS 2 code, so it does use `idlc` when building for native.

What I think I'll do for now is to disable the Struct32k tests in there, as that is the only one causing a problem (I think).  We can re-enable it when we switch to a newer version of CycloneDDS.

**Comment by eboasson** [comment] 2022-06-23 14:45
Humble uses 0.9 and that includes #903 mentioned above by @dpotman. That solves the problem (just double-checked it locally). That means I see no reason to keep this issue open. (As always, feel free re-open if needed.)

**Closed by eboasson** 2022-06-23 14:45 UTC
