### ISSUE TITLE
Unable to build Cyclone DDS on Ubuntu 18.04

### ISSUE THREAD

**Issue by evshary** [eclipse-cyclonedds/cyclonedds#546] opened 2020-06-15 02:15 UTC
I try to build Cyclone DDS on Ubuntu 18.04.
However, I find that there is the error message while building.

```bash
$ git clone https://github.com/eclipse-cyclonedds/cyclonedds.git
$ cd cyclonedds
$ mkdir build && cd build
$ cmake ..

......(ignore some message)

-- Found Maven: /usr/bin/mvn (found suitable version "3.6.0", minimum required is "3.0") 
-- Found Java: /usr/bin/java (found suitable version "11.0.7", minimum required is "1.8") 
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY
CMake Error at /usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake:97 (try_compile):
  Unknown extension ".cxx" for file

    /home/chenying/workspace/cyclonedds/build/CMakeFiles/CMakeTmp/src.cxx

  try_compile() works only for enabled languages.  Currently these are:

    C

  See project() command to enable other languages.
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/CheckCXXCompilerFlag.cmake:49 (CHECK_CXX_SOURCE_COMPILES)
  /usr/share/cmake-3.10/Modules/GenerateExportHeader.cmake:215 (check_cxx_compiler_flag)
  /usr/share/cmake-3.10/Modules/GenerateExportHeader.cmake:374 (_test_compiler_hidden_visibility)
  src/security/builtin_plugins/access_control/CMakeLists.txt:23 (generate_export_header)


-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY - Failed
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY

......(ignore some message)
```

I guess the error is related to [the issue](https://gitlab.kitware.com/cmake/cmake/-/issues/16967) in CMAKE project. It's fixed in [the PR](https://gitlab.kitware.com/cmake/cmake/-/merge_requests/1799/diffs).
Maybe CMAKE in Ubuntu 18.04 haven't had the bugfix yet.

**Comment by eboasson** [comment] 2020-06-15 08:08
Oh dear. Yes, Ubuntu LTS releases stick to the ancient version of CMake they were released with (mistakenly, in my view) and that is compounded by CMake versions being ancient within a month of their release (or so it seems) and their choices making little sense anyway (to me at least).

I suppose we could simply require a sufficiently recent version of CMake, now that Ubuntu 20.04 is commonly available and targetted by ROS2. While I think it is important to maintain run-time compatibility with old platforms if there is no compelling reason to drop it, requiring reasonably recent versions of build tools (and specifically CMake) is a slightly different story.

But perhaps the following would work, too. It seems it work on macOS with a recent CMake, but who knows what it does on Ubuntu 18.04 with an old CMake ... Could you give it a try?
```CMake
set(_languages C)
if (CMAKE_VERSION VERSION_LESS 3.13)
  set(_languages C CXX)
endif()
project(CycloneDDS VERSION 0.7.0 LANGUAGES ${_languages})
```

@k0ekk0ek what's your view on this?

**Comment by k0ekk0ek** [comment] 2020-06-15 08:10
Haha, beat me to the punch @eboasson. Was just about to type:

Hi @evshary! We merged this PR #541 last week, which causes this issue. I was afraid we were going to run into trouble and now I recall the issue with the addition of `LANGUAGES C`.

I'll have a look. The above might work, maybe we can add the CMake module locally. I'll try a few approaches and see what works best.

**Comment by k0ekk0ek** [comment] 2020-06-15 12:15
@evshary, the problem is solved (see #547), but before it can be merged to master we have to go through the Eclipse CQ process. Shouldn't be a problem since it's licensed under the 3-Clause BSD License, but until then, please grab the patch from the PR. Thanks for reporting the issue, it's very much appreciated :+1:

**Comment by evshary** [comment] 2020-06-16 01:52
@k0ekk0ek and @eboasson  Thanks for your quick bugfix. The patch works well in my environment.
Feel free to close the issue if the PR is merged.

**Comment by clalancette** [comment] 2020-06-16 13:50
I'll just point out that I'm also hitting this, so I'd love to see #547 merged.

**Comment by eboasson** [comment] 2020-06-16 13:58
The Eclipse CQ process sometimes goes very quickly and sometimes not-so-quickly, because it is involves volunteers. The temporary workaround is self-evident, I'd think, which is to just remove the "LANGUAGES C" part from the `project` lines.

**Comment by robinlinden** [comment] 2020-06-18 23:07
Ah, sorry about that. I tested it on semi-old Ubuntu, but I usually install a newer cmake using pip, I completely missed it. :/

Another solution similar to the 
```
set(_languages C)
if (CMAKE_VERSION VERSION_LESS 3.13)
  set(_languages C CXX)
endif()
project(CycloneDDS VERSION 0.7.0 LANGUAGES ${_languages})
```
is to do something like
```
project(CycloneDDS VERSION 0.7.0 LANGUAGES C)
if (CMAKE_VERSION VERSION_LESS 3.13)
  enable_languages(CXX)
endif()
```
Very similar, but maybe less likely to confuse ancient tooling?

**Comment by eboasson** [comment] 2020-06-19 08:09
I like this trick! @k0ekk0ek knows CMake better than I do, so let's see what he says.

**Comment by k0ekk0ek** [comment] 2020-06-19 08:23
I hadn't encountered [enable_language](https://cmake.org/cmake/help/latest/command/enable_language.html) before. It's not exactly the same as overriding the CMake module for older versions. With this, the check is still done on the C++ compiler as opposed to the chosen C compiler (see the [PR](https://gitlab.kitware.com/cmake/cmake/-/merge_requests/1799/diffs) mentioned by @evshary), but I doubt it matters in practice. I'll issue a quick PR and drop #547. Thanks @robinlinden. It's an excellent workaround.

**Closed** 2020-06-19 11:21 UTC
