### ISSUE TITLE
idlc: Wrong memory alloc/free between dll and exe

### ISSUE THREAD

**Issue by Pro** [eclipse-cyclonedds/cyclonedds#1585] opened 2023-02-28 05:57 UTC
I am currently updating a conan recipe for cyclonedds, and as part of this, I'm building on Windows with compiler runtime MTd.

Used Version: Current master branch ()

I'm hitting the following error during compilation:

```
---------------------------
Microsoft Visual C++ Runtime Library
---------------------------
Debug Assertion Failed!

Program: C:\.conan\b8fe73\1\build\bin\Debug\ddsc.dll
File: minkernel\crts\ucrt\src\appcrt\heap\debug_heap.cpp
Line: 996

Expression: __acrt_first_block == header

For information on how your program can cause an assertion
failure, see the Visual C++ documentation on asserts.

(Press Retry to debug the application)

---------------------------
Abort   Retry   Ignore   
---------------------------
```

![image](https://user-images.githubusercontent.com/251973/221766285-7ca29a10-f137-44a9-bc5f-bfecd69128ce.png)

As you can see in the screenshot this happens when calling idlc.exe.

The error message typically means that the memory allocations do not match, i.e., malloc is done in the .exe, while free is done in the .dll (or the other way around).

The master branch should already include the fixes from https://github.com/eclipse-cyclonedds/cyclonedds/pull/1438

Seems there is still at least one place where malloc/free are not properly called via `idl_malloc` and `idl_free`

**Comment by eboasson** [comment] 2023-03-01 12:18
Closing as a duplicate of #1586 where more information is available. (I do hope I did not overlook a detail here that makes it different. If I did, please reopen!)

**Closed by eboasson** 2023-03-01 12:18 UTC

**Comment by Pro** [comment] 2023-03-01 14:24
Ah, jep, sorry, Github had a Hiccup and pisted the same issue report two times. You can even delete this issue.
