### ISSUE TITLE
Five Pub(five Topic), and Five Sub;  It will lost some msg sometimes

### ISSUE THREAD

**Issue by Billlloves** [eclipse-cyclonedds/cyclonedds#165] opened 2019-04-24 13:20 UTC
Hi! , I created two apps. A created a participant , 5 publishers(different topic for each one).  B created a participant, 5 sub(5 diff topics) . Sometimes not all of the subs can get the msg.  
What happened there?

**Comment by eboasson** [comment] 2019-04-24 13:50
Hi, that's precious little information, but there are two typical ways for running into this problem:
* One is to accidentally use best-effort instead of reliable communication: the default QoS setting for topics and for data readers is best-effort in the DDS spec — the setting for data writers is reliable, though! — and so it is quite possible that you accidentally created a best-effort data path. Actually I am very tempted to change the default in Cyclone to always default to reliable communications — I should make a ticket for that and see what the community thinks.
Typically, if the subscribers are fast enough to keep up with the writers, the amount of data loss with a best-effort setting is negligible with wired networks.
* The other is to have a reliability setting of KEEP_LAST with a depth of (typically) 1. This is also the default setting. With a KEEP_LAST history, newer data overwrites older data for the same key value, so if your reader doesn't keep up with your writer (for whatever reason) you'll lose some samples.
In this, "not keeping up" could also be a writer that publishes a few samples rather quickly and the reader reads only once per second.

I'd check those two things first, if I were you.

**Comment by Billlloves** [comment] 2019-04-25 01:46
Hi, thanks for giving me those two things. 
The implement is like this：
![image](https://user-images.githubusercontent.com/39365642/56703943-d4a8a980-673d-11e9-9dd6-3fe1fd40d172.png)

After they fond  each other, each pub only send one msg to the sub. Sometimes only two subs can get the msg, but all the pubs had sent the msgs.
ps: All of them are using default Qos.

**Comment by eboasson** [comment] 2019-04-25 20:28
@Billlloves, in my reading of the specification, there is no full handshake between a reader and a writer and for volatile data you're therefore only guaranteed to receive the data once (1) the writer has matched the reader and (2) the reader has matched the writer. Until both are the case, the data may still be dropped.

In practice, you can fairly easily account for (1) in the publishing process, but (2) is a rather troublesome thing because it is in a different process. This is not a problem DDS — and so Cyclone — should dump on the application.

For example if you would do:
```
wr = dds_create_writer
wait until there is a matching reader
dds_write(wr, ...)
```
you'd expect that matching reader to receive that one sample. However, if that reader has not yet discovered the writer, it can still drop the sample.

I'm guessing this fits with what you are seeing. If it is, then the data should consistently arrive if you add a sleep. Not that I would suggest that is a good solution, but it does make sense to test the hypothesis.

Note that while I do believe the current behaviour of Cyclone is allowed, it is also very counter-intuitive. I believe there are some ways within the spec — it has to be interoperable — to actually guarantee that that sample will arrive, and so that's something I intend to change in Cyclone.

**Comment by Billlloves** [comment] 2019-05-13 01:59
wr = dds_create_writer
wait until there is a matching reader
dds_write(wr, ...)

actually this is what I've done. All of them printed connected. 

I wrote two samples then, and found that:
Sample1:
    In one thread, created five topics and writers. After they found the matching reader and the reader found the writer too. then cent the msg. Mostly readers can get msg. But sometimes one or two msgs lost.
Sample2:
   Created five threads. Each thread contains one topic and one writer, and the same way in Readers. In this situation， Mostly reader can not get the msg.

**Comment by eboasson** [comment] 2019-05-13 14:33
I really want to understand exactly what is going on here — perhaps it is the known issue with matching taking time and it being possible that data gets discarded by the reader if it arrives to early, &c. — but perhaps it is not. Either way, it needs fixing ...

Would it be possible to share your two samples? Then I'll run them myself and have a good look.

**Comment by eboasson** [comment] 2019-05-20 12:28
Hi @Billlloves,

Found it … not exactly the same as fixed it, but progress nonetheless. The problem with _finding_ it turned out to be a short sleep in a loop waiting for the “publication matched” event and my having overlooked it previously … and that those few milliseconds were enough for the problem to not occur.

It is related to the old “known issue” I referred to, but in a new manifestation. It used to be virtually impossible to trigger in practice, but it has become pretty easy to trigger (as you have shown) because of two separate changes, both with good reason.

An easy way to work around the problem you ran into is to accept a new volatile reader possibly receiving some old data from a volatile writer. That won’t fly for a transient-local writer with a volatile reader, so it means keeping the current behaviour for a volatile reader with a transient-local writer. Therefore with this band-aid, if you were to “upgrade” the writer to transient-local, it would “downgrade” the completeness of the data set presented by the reader … so this change is not a proper solution, but I’m giving it here in case it really helps you:

```diff
diff --git a/src/core/ddsi/src/q_receive.c b/src/core/ddsi/src/q_receive.c
index 842d372..3e97ff6 100644
--- a/src/core/ddsi/src/q_receive.c
+++ b/src/core/ddsi/src/q_receive.c
@@ -1200,17 +1200,20 @@ static int handle_Heartbeat (struct receiver_state *rst, nn_etime_t tnow, struct
     struct nn_rsample_chain sc;
     int refc_adjust = 0;
     nn_reorder_result_t res;
-
-    nn_defrag_notegap (pwr->defrag, 1, lastseq + 1);
-    gap = nn_rdata_newgap (rmsg);
-    if ((res = nn_reorder_gap (&sc, pwr->reorder, gap, 1, lastseq + 1, &refc_adjust)) > 0)
+    const seqno_t refseq = (pwr->c.xqos->durability.kind == NN_VOLATILE_DURABILITY_QOS) ? firstseq : lastseq + 1;
+    if (refseq >= 1)
     {
-      if (pwr->deliver_synchronously)
-        deliver_user_data_synchronously (&sc);
-      else
-        nn_dqueue_enqueue (pwr->dqueue, &sc, res);
+      nn_defrag_notegap (pwr->defrag, 1, refseq);
+      gap = nn_rdata_newgap (rmsg);
+      if ((res = nn_reorder_gap (&sc, pwr->reorder, gap, 1, refseq, &refc_adjust)) > 0)
+      {
+        if (pwr->deliver_synchronously)
+          deliver_user_data_synchronously (&sc);
+        else
+          nn_dqueue_enqueue (pwr->dqueue, &sc, res);
+      }
+      nn_fragchain_adjust_refcount (gap, refc_adjust);
     }
-    nn_fragchain_adjust_refcount (gap, refc_adjust);
     pwr->have_seen_heartbeat = 1;
   }

```

That works for me 😊

What follows is a little bit of background information. Feel free to skip it if you’d rather not know!

Those aforementioned two changes are:

* b14663c1735f4543cf9c1bf497c361f2f3d85f5c, which drops any incoming data until a Heartbeat has been received because if all you know about writer is a single Data message you just received, you just don’t know enough to accept it as a starting point for the reader:
  * It may have been a retransmit — so too old, and accepting it could result in a gap in the sequence numbers later on, even though the writer and reader are both using a KEEP_ALL policy.
  * It may also be that it is a fresh sample, but that doesn’t mean it is the first sample to have been sent by the writer since matching the new reader: it may be “just luck”, in that grey area during discovery, where you just happen to pick up a multicasted packet that makes perfect sense but without a guarantee that the writer is already aware of the new reader.
  * Equally, it may be that you were supposed to get the preceding sample, but it happened to be in a packet that got lost, and so you would be incorrect in treating the first received one as something already deliverable. (You could stash it away until you know more, but that doesn’t change to the argument.)

* 72c1920eed776a3640c08686bdf3e89e40d83b45, which came because  it was observed that sometimes you’d see historical data for a transient-local reader also show up in a volatile reader (#146). That one introduces a clear distinction between historical and fresh data based on the first Heartbeat it receives, and simply uses the writer’s _next sequence number_ as the starting point for fresh data, treating everything before that as historical. Arguably correct, but in combination with the other change, it just so happens that it ignores that first sample when it initially arrives, and the piggy-backed Heartbeat that follows it in the same packet then sets things up so that it will receive the next sample as the first fresh (or, in a way, “volatile”) one. Thus, sample 1 lost …

I would say there are three components (short of simple blunders) that cause the problem. The first is in the specification — not so much that it is incorrect, but it depends on how you read it and what interpretative freedom you believe justified; the second is a design choice in this DDSI stack; and the third is a piece in the implementation that has never yet been completed.

The **specification** builds up the reliable and transient-local history protocol from a few components: the writer history cache (WHC), that contains samples available for retransmit; Heartbeat messages in which a writer indicates the oldest sequence number available in its WHC and the highest sequence number it has ever written; and AckNack messages that indicate up to which sequence number everything has been received by a reader + optionally some requests for retransmission. AckNacks are only sent in response to Heartbeats, and Heartbeats are essentially sent at the writer’s discretion (as long as there is always a Heartbeat in the near future while there is unacknowledged data — the spec says “periodically”, but that without any further details on what that means exactly).

So consider a volatile keep-all writer that is writing samples once there is one matched reader R1 (no difficult cases involved), and then a second one R2, shows up. If the writer is ahead of R1 by a good number of samples (e.g., sending many small samples you have to be or the you’ll never get decent throughput), it will have a large number of samples in its WHC.

Now R2 shows up, and it receives a Heartbeat from the writer. This will then give a range of sequence numbers, e.g., [N-999,N] if the last 1000 ones written are still available. Quite likely, N-999 was written before R2 was matched and so is historical data for R2. Conversely, N may will have been written after R2 was matched, but that doesn’t mean R2 ever received it. It is impossible for R2 to know what the first sequence number is that the writer sent after it matched it. Arguing that you can ignore the problem is arguing for something counter-intuitive at best, and I’ve long since decided that this point must become precise in Cyclone.

One could let the writer sent a Heartbeat just to R2 in which it claims something other than what it is supposed to claim: it could send a Heartbeat with the oldest available sequence number set to the first sample that was written after R2 was matched. That should be ok, it is addressed only to R2 after all, but it is not standardised behaviour and so would require a Cyclone-special.

One could also just request all the historical data, and let the writer send a Gap message instead of Data messages for all sequence numbers that are really just historical data for R2 (that would just be a single Gap message, which is small). That would be fairly efficient. This, too, isn’t required behaviour by the spec.

Both cases require deviating from something that is mostly true in the spec: the contents of the messages are, generally, universally valid and the destination information is more an optimisation than a relevant detail. Either of the above two ways gets you away from that.

The **design choice** in this DDSI stack is to not treat multiple readers for the same topic as completely independent things. The argument behind that is that the vast majority of the time, all DDS is doing is pushing fresh data through the system, to be processed equally by all those (DDSI/DDS) readers and presented to the application. Thus, there is gain to be had by performing the processing for incoming samples only once, then delivering to all local readers in one go.

There are obvious exceptions: historical data for new transient-local readers, and readers that have hit some resource limit. The first is currently implemented by providing an asynchronous bypass path for “old” data. That adds significant complexity, and it isn’t quite right today because the ordering changes. There is also the issue that you can have both a transient-local and a volatile reader matching the same writer; or a combination of best-effort and reliable readers. That all really complicates this arrangement — but I really like the almost negligible incremental cost of a data reader.

Note that the problems all disappear if the writer sent a Heartbeat prior to creating the first reader: by then the receiving already knows the sequence from which the new reader should start receiving data.

The **implementation** issue is that the case where the reader is behind the writer and starts catching up while maintaining order is not implemented yet. Most of the bits and pieces are in place, but they aren’t actually used yet and there are some details to be filled in. This was meant to be used when a single reader hit a resource limit — flip its mode, allow it to recover while the rest keeps running smoothly, and flip it back once it catches up. As it isn’t quite there yet, running into a resource limit is handled a bit less elegantly — causing very minor trouble if the reader takes the data shortly, but really big trouble if it never does. It so happens that exactly this missing part of the stack would solve (1) a transient-local historical data ordering issue that currently exists and (2) work nicely with the approach where the writer sends a Gap for any samples not relevant for that one reader. Each new reader matching a proxy writer for which no Heartbeat has been received yet then simply starts as “out-of-order” from sequence number 1.

So it appears that implementing that one missing allows addressing three things in one go: ordering of transient-local history, resource limits handling and this problem of possibly losing the first (few) samples written immediately after the “publication matched” event.

**Comment by eboasson** [comment] 2019-05-31 05:52
@Billlloves , this should be fixed. You have probably seen the notification already.

I'll close the issue, but please reopen it or create a new one if you still have problems.

**Closed by eboasson** 2019-05-31 05:52 UTC

**Comment by Billlloves** [comment] 2019-07-01 09:25
thanks a lot, I'll check it again

**Comment by Billlloves** [comment] 2019-07-01 09:34
> Hi @Billlloves,
> 
> Found it … not exactly the same as fixed it, but progress nonetheless. The problem with _finding_ it turned out to be a short sleep in a loop waiting for the “publication matched” event and my having overlooked it previously … and that those few milliseconds were enough for the problem to not occur.
> 
> It is related to the old “known issue” I referred to, but in a new manifestation. It used to be virtually impossible to trigger in practice, but it has become pretty easy to trigger (as you have shown) because of two separate changes, both with good reason.
> 
> An easy way to work around the problem you ran into is to accept a new volatile reader possibly receiving some old data from a volatile writer. That won’t fly for a transient-local writer with a volatile reader, so it means keeping the current behaviour for a volatile reader with a transient-local writer. Therefore with this band-aid, if you were to “upgrade” the writer to transient-local, it would “downgrade” the completeness of the data set presented by the reader … so this change is not a proper solution, but I’m giving it here in case it really helps you:
> 
> ```diff
> diff --git a/src/core/ddsi/src/q_receive.c b/src/core/ddsi/src/q_receive.c
> index 842d372..3e97ff6 100644
> --- a/src/core/ddsi/src/q_receive.c
> +++ b/src/core/ddsi/src/q_receive.c
> @@ -1200,17 +1200,20 @@ static int handle_Heartbeat (struct receiver_state *rst, nn_etime_t tnow, struct
>      struct nn_rsample_chain sc;
>      int refc_adjust = 0;
>      nn_reorder_result_t res;
> -
> -    nn_defrag_notegap (pwr->defrag, 1, lastseq + 1);
> -    gap = nn_rdata_newgap (rmsg);
> -    if ((res = nn_reorder_gap (&sc, pwr->reorder, gap, 1, lastseq + 1, &refc_adjust)) > 0)
> +    const seqno_t refseq = (pwr->c.xqos->durability.kind == NN_VOLATILE_DURABILITY_QOS) ? firstseq : lastseq + 1;
> +    if (refseq >= 1)
>      {
> -      if (pwr->deliver_synchronously)
> -        deliver_user_data_synchronously (&sc);
> -      else
> -        nn_dqueue_enqueue (pwr->dqueue, &sc, res);
> +      nn_defrag_notegap (pwr->defrag, 1, refseq);
> +      gap = nn_rdata_newgap (rmsg);
> +      if ((res = nn_reorder_gap (&sc, pwr->reorder, gap, 1, refseq, &refc_adjust)) > 0)
> +      {
> +        if (pwr->deliver_synchronously)
> +          deliver_user_data_synchronously (&sc);
> +        else
> +          nn_dqueue_enqueue (pwr->dqueue, &sc, res);
> +      }
> +      nn_fragchain_adjust_refcount (gap, refc_adjust);
>      }
> -    nn_fragchain_adjust_refcount (gap, refc_adjust);
>      pwr->have_seen_heartbeat = 1;
>    }
> ```
> 
> That works for me 
> 
> What follows is a little bit of background information. Feel free to skip it if you’d rather not know!
> 
> Those aforementioned two changes are:
> 
> * [b14663c](https://github.com/eclipse-cyclonedds/cyclonedds/commit/b14663c1735f4543cf9c1bf497c361f2f3d85f5c), which drops any incoming data until a Heartbeat has been received because if all you know about writer is a single Data message you just received, you just don’t know enough to accept it as a starting point for the reader:
>   
>   * It may have been a retransmit — so too old, and accepting it could result in a gap in the sequence numbers later on, even though the writer and reader are both using a KEEP_ALL policy.
>   * It may also be that it is a fresh sample, but that doesn’t mean it is the first sample to have been sent by the writer since matching the new reader: it may be “just luck”, in that grey area during discovery, where you just happen to pick up a multicasted packet that makes perfect sense but without a guarantee that the writer is already aware of the new reader.
>   * Equally, it may be that you were supposed to get the preceding sample, but it happened to be in a packet that got lost, and so you would be incorrect in treating the first received one as something already deliverable. (You could stash it away until you know more, but that doesn’t change to the argument.)
> * [72c1920](https://github.com/eclipse-cyclonedds/cyclonedds/commit/72c1920eed776a3640c08686bdf3e89e40d83b45), which came because  it was observed that sometimes you’d see historical data for a transient-local reader also show up in a volatile reader (#146). That one introduces a clear distinction between historical and fresh data based on the first Heartbeat it receives, and simply uses the writer’s _next sequence number_ as the starting point for fresh data, treating everything before that as historical. Arguably correct, but in combination with the other change, it just so happens that it ignores that first sample when it initially arrives, and the piggy-backed Heartbeat that follows it in the same packet then sets things up so that it will receive the next sample as the first fresh (or, in a way, “volatile”) one. Thus, sample 1 lost …
> 
> I would say there are three components (short of simple blunders) that cause the problem. The first is in the specification — not so much that it is incorrect, but it depends on how you read it and what interpretative freedom you believe justified; the second is a design choice in this DDSI stack; and the third is a piece in the implementation that has never yet been completed.
> 
> The **specification** builds up the reliable and transient-local history protocol from a few components: the writer history cache (WHC), that contains samples available for retransmit; Heartbeat messages in which a writer indicates the oldest sequence number available in its WHC and the highest sequence number it has ever written; and AckNack messages that indicate up to which sequence number everything has been received by a reader + optionally some requests for retransmission. AckNacks are only sent in response to Heartbeats, and Heartbeats are essentially sent at the writer’s discretion (as long as there is always a Heartbeat in the near future while there is unacknowledged data — the spec says “periodically”, but that without any further details on what that means exactly).
> 
> So consider a volatile keep-all writer that is writing samples once there is one matched reader R1 (no difficult cases involved), and then a second one R2, shows up. If the writer is ahead of R1 by a good number of samples (e.g., sending many small samples you have to be or the you’ll never get decent throughput), it will have a large number of samples in its WHC.
> 
> Now R2 shows up, and it receives a Heartbeat from the writer. This will then give a range of sequence numbers, e.g., [N-999,N] if the last 1000 ones written are still available. Quite likely, N-999 was written before R2 was matched and so is historical data for R2. Conversely, N may will have been written after R2 was matched, but that doesn’t mean R2 ever received it. It is impossible for R2 to know what the first sequence number is that the writer sent after it matched it. Arguing that you can ignore the problem is arguing for something counter-intuitive at best, and I’ve long since decided that this point must become precise in Cyclone.
> 
> One could let the writer sent a Heartbeat just to R2 in which it claims something other than what it is supposed to claim: it could send a Heartbeat with the oldest available sequence number set to the first sample that was written after R2 was matched. That should be ok, it is addressed only to R2 after all, but it is not standardised behaviour and so would require a Cyclone-special.
> 
> One could also just request all the historical data, and let the writer send a Gap message instead of Data messages for all sequence numbers that are really just historical data for R2 (that would just be a single Gap message, which is small). That would be fairly efficient. This, too, isn’t required behaviour by the spec.
> 
> Both cases require deviating from something that is mostly true in the spec: the contents of the messages are, generally, universally valid and the destination information is more an optimisation than a relevant detail. Either of the above two ways gets you away from that.
> 
> The **design choice** in this DDSI stack is to not treat multiple readers for the same topic as completely independent things. The argument behind that is that the vast majority of the time, all DDS is doing is pushing fresh data through the system, to be processed equally by all those (DDSI/DDS) readers and presented to the application. Thus, there is gain to be had by performing the processing for incoming samples only once, then delivering to all local readers in one go.
> 
> There are obvious exceptions: historical data for new transient-local readers, and readers that have hit some resource limit. The first is currently implemented by providing an asynchronous bypass path for “old” data. That adds significant complexity, and it isn’t quite right today because the ordering changes. There is also the issue that you can have both a transient-local and a volatile reader matching the same writer; or a combination of best-effort and reliable readers. That all really complicates this arrangement — but I really like the almost negligible incremental cost of a data reader.
> 
> Note that the problems all disappear if the writer sent a Heartbeat prior to creating the first reader: by then the receiving already knows the sequence from which the new reader should start receiving data.
> 
> The **implementation** issue is that the case where the reader is behind the writer and starts catching up while maintaining order is not implemented yet. Most of the bits and pieces are in place, but they aren’t actually used yet and there are some details to be filled in. This was meant to be used when a single reader hit a resource limit — flip its mode, allow it to recover while the rest keeps running smoothly, and flip it back once it catches up. As it isn’t quite there yet, running into a resource limit is handled a bit less elegantly — causing very minor trouble if the reader takes the data shortly, but really big trouble if it never does. It so happens that exactly this missing part of the stack would solve (1) a transient-local historical data ordering issue that currently exists and (2) work nicely with the approach where the writer sends a Gap for any samples not relevant for that one reader. Each new reader matching a proxy writer for which no Heartbeat has been received yet then simply starts as “out-of-order” from sequence number 1.
> 
> So it appears that implementing that one missing allows addressing three things in one go: ordering of transient-local history, resource limits handling and this problem of possibly losing the first (few) samples written immediately after the “publication matched” event.

thx a lot , I'll check it again
