### ISSUE TITLE
Configuring corporate wifi for turtlebot4 via cyclone DDS

### ISSUE THREAD

**Issue by Srimathi-tw** [eclipse-cyclonedds/cyclonedds#1421] opened 2022-09-29 06:22 UTC
**System information**

**OS:** Ubuntu 20.04
**ROS Distro:** Galactic

**Steps to reproduce**
1. Follow network configuration in [https://turtlebot.github.io/turtlebot4-user-manual/overview/quick_start.html](https://turtlebot.github.io/turtlebot4-user-manual/overview/quick_start.html)
2. Using 
```
<CycloneDDS>
  <Domain>
    <Id>any</Id>
    <General>
      <NetworkInterfaceAddress>auto</NetworkInterfaceAddress>
      <AllowMulticast>false</AllowMulticast>
      <EnableMulticastLoopback>true</EnableMulticastLoopback>
    </General>
    <Discovery>
      <ParticipantIndex>0</ParticipantIndex>
      <Peers>
        <Peer Address="${ROBOT_IP}:7410"/>
      </Peers>
    </Discovery>
  </Domain>
</CycloneDDS>

```

and export the file path in `CYCLONEDDS_URI`
and replace `{ROBOT_IP}` with the bot ip_address this is specific to corporate wifi configuration(reference [https://iroboteducation.github.io/create3_docs/setup/xml-config/](https://iroboteducation.github.io/create3_docs/setup/xml-config/) )

**Other Notes**
We tried changing ```<NetworkInterfaceAddress>auto</NetworkInterfaceAddress>``` with our interface address as well

**Comment by eboasson** [comment] 2022-10-06 17:10
It is not clear to me what the problem is exactly, though I suspect you're not able to communicate with the robot.

Would it be possible to give a little bit more detail in what you are seeing (or not seeing) and provide some logs or packet captures? Thanks!

**Comment by thijsmie** [comment] 2022-12-07 09:03
No more feedback was given, we can't tell what the actual problem is, closing.

**Closed by thijsmie** 2022-12-07 09:03 UTC
Labels: waiting-on-feedback
