### ISSUE TITLE
Reduce how eager CycloneDDS is in retransmits

### ISSUE THREAD

**Issue by clalancette** [eclipse-cyclonedds/cyclonedds#484] opened 2020-04-10 13:25 UTC
We've been testing out CycloneDDS with ROS 2 Foxy prerelease (commit hash 45c0f432a9c72fddf1ae0cce4761e8a92cb567e4 of this repository).  Our particular test is an stereo image to pointcloud pipeline.   There is a trigger at one end; when the trigger topic is published, it causes two images to be generated from simulated Gazebo cameras.  Each of those images is 640x480x3 (921600 bytes).  Those two images are published to a node to do disparity processing, and then that output is published to a node to generate a pointcloud.  Finally, the pointcloud is published and we subscribe to print out parts of it.  That final pointcloud is 9830400 bytes.  There's an example of this pipeline at https://github.com/jacobperron/pc_pipe (along with a README on how to run).

When we run this pipeline with CycloneDDS (all on the same machine), we see that most of the time, the pipeline finishes fairly quickly (< 300 ms).  However, sometimes it takes the pipeline a *very* long time to complete; I've had to wait up to 100 seconds to get a final pointcloud.  When I instrumented, I found that most of that time seems to be spent in the publication of the large final pointcloud.

I discussed this with @eboasson offline, and he recommended that I try some tuning to narrow down the problem.  Towards that end, I increased my /proc/sys/net/core/rmem_max to 30MB, and then instructed CycloneDDS to ask for very large receive buffers with the following XML:

```
<?xml version="1.0" encoding="UTF-8" ?>
<CycloneDDS xmlns="https://cdds.io/config" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://cdds.io/config https://raw.githubusercontent.com/eclipse-cyclonedds/cyclonedds/master/etc/cyclonedds.xsd">
    <Domain id="any">
        <Internal>
            <MinimumSocketReceiveBufferSize>20MB</MinimumSocketReceiveBufferSize>
        </Internal>
    </Domain>
</CycloneDDS>
```

With that in place, the long delays are absolutely gone; in 2000 tries, I never had to wait more than 400ms from the initial trigger to the final pointcloud.

Now, the above is a workaround; it requires both root (something not everyone has), and also requires that you know a priori what your largest message size is.  After further discussion with Erik, it seems like Cyclone is being a bit too eager in its retransmissions.  I believe he mentioned that someone is looking into this, but this issue is just to open the problem for visibility.  Please let me know if you need any more information from me about the setup, or additional testing.  I'm happy to provide it.

**Comment by clalancette** [comment] 2020-04-22 20:36
Just checking in whether there's been any movement on this issue?  If there is anything available for us to test, I'm happy to do that.  Thanks.

**Comment by eboasson** [comment] 2020-04-23 06:10
Hi @clalancette, I have indeed asked a colleague to look into it and he told me earlier this week he sees exactly the same behaviour and is now investigating ways to fix it. I'll try to be better in keeping you posted, but if it stays quiet for too long, please do not hesitate to ask again.

**Comment by clalancette** [comment] 2020-04-23 12:31
Great, thanks for the update!

**Comment by BartP6703** [comment] 2020-05-06 07:51
I did some further investigation:

Limiting the number of bytes that are retransmitted by sending only the first 100k of the 10Mb samples. This way the number of retransmits should decrease significantly and the throughput should be lower than in the original situation but without the drop in throughput.

After the limitation of sending only 100k the throughput becomes constant but is very low (only a few megabytes i.s.o. several hundreds of megabytes).

**Comment by eboasson** [comment] 2020-05-06 08:42
@BartP6703 thanks for looking into it and experimenting with sending smaller amounts at a time. I agree that limiting the amount of data that is sent is the smart thing to do, however with 100kB blocks that drop in throughput you noted is way too big: with a few simple assumptions of
* a latency of 20µs (the exact number doesn't matter, this should be close enough for loopback and GbE);
* no packet loss (in the absence of buffer overruns, that's pretty realistic for loopback and GbE);

and a very simple model of sending 100kB, waiting for an retransmit request [\*], sending the next 100kB &c., a 10MB sample would incur approximately 100*20µs=2ms additional latency over streaming at full rate. On GbE, 10MB takes ~100ms so those 2ms correspond to a ~2% drop — not a precipitous drop to a few MB/s. On loopback the numbers work out a bit differently because loopback throughput is way higher (as you noted: "several hundreds of megabytes"), but at an assumed 1GB/s throughput, it would be "only" 20%. A steep drop, but to 800MB/s or so.

There is only one possible conclusion: it needs a bit more digging. I would look at the network utilisation while doing your test:
* If the network utilization fits with the observed data throughput, then it is just waiting all the time, and the trick is to make it request data sooner;
* If the network utilization is much higher, then it is likely to be retransmitting things that shouldn't be retransmitted.

I suspect it is the first of the two. In that case the thing to look at is what ranges of sequence numbers are being advertised in HEARBEAT and HEARTBEATFRAG messages. Just sending the first 100kB and then stopping will likely result in the receiver waiting for far too long before concluding it should request more [\*\*]. Secondly, if a retransmit request of the receiver does not get responded to in full, the receiver will (probably) wait a bit with requesting again.

I think this would all be quite visible in a Wireshark capture (or in a Cyclone DDS trace). Alternatively, you might want to add a few `printf`s in `handle_AckNack`, `handle_NackFrag`, `handle_Heartbeat`, `handle_HeartbeatFrag` and `handle_xevk_acknack` considering that those are the key functions involved in deciding retransmits.

Hopefully this is of some use to you. Feel free to share more observations while you continue the investigation. It is not a trivial protocol stack and so I might be able to make sense of a pattern simply because I know the code "quite" well.

[\*] DDSI-RTPS only retransmits based on a retransmit request, so merely acknowledging the data that has been received is not enough. Worse, the way large samples are transmitted means there is no standardized way to inform the sender that you have received, say the first 50% of a sample. It would probably be a reasonable assumption that a retransmit requestion starting at 50% means the first 50% has been received, and once everything has been received, you get an acknowledgement for the full sample. It is really weird quirk of the protocol ...

[\*\*] DDSI-RTPS only allows sending a retransmit request in response to a HEARTBEAT or HEARTBEATFRAG ... more quirks ...

**Comment by clalancette** [comment] 2020-05-13 20:08
Just checking in whether there are any proposed fixes pending that we could test out here?  Thanks.

**Comment by eboasson** [comment] 2020-05-18 14:11
Hi @clalancette, sorry for the tardy response, we've been rather swamped ... The good thing is that there is progress: despite running into some initial snags, it now seems to behave properly (at least in the 10MB case with small buffers), but it needs some cleaning up and certainly also some more testing to verify there are no surprises if one starts changing test parameters. So it needs a bit more time still.

**Comment by clalancette** [comment] 2020-05-19 16:41
Great, thanks for the continued updates.

**Comment by eboasson** [comment] 2020-05-29 16:41
Hi @clalancette, I've been playing around with it for a bit and https://github.com/eboasson/cyclonedds/tree/rexmit-improvements behaves much better with large samples, at least in the cases I tried. You might want to give it a try: it should work, but as we all know stuff can happen when you try some other scenario.

There is a curious thing going on with the sanity check it runs on Travis and this is what causes the CI failures. That check does a combined throughput and roundtrip test, and checks whether the rates meet some experimentally determined thresholds. With the new version, the number of roundtrips is lower and sometimes (the failure cases) even below the threshold. When I run it locally, I also see this reduction in roundtrips, but with a clear shift towards higher throughput. It seems to me I need to figure out what exactly is going on, but it doesn't necessarily mean there's a bug.

For reference, on my Linux VM (so not a representative platform), running a throughput test with 30s of 100B samples followed by 30s of 100kB, then 30s of 1MB and finally 30s of 10MB (blue is raw bandwidth over 1s, ochre DDS sample bandwidth over 1s, blue same over 10s), I used to get:

![image](https://user-images.githubusercontent.com/16984005/83282800-6ce34e80-a1da-11ea-9245-278ebb3ce9f5.png)

and now:

![image](https://user-images.githubusercontent.com/16984005/83282824-72d92f80-a1da-11ea-858d-a8d18772183d.png)

(I adjusted some configuration settings that seemed like I could safely do that now, but the "before" case has the corresponding changes applied).

From a a 64-bit Pi3 to my MacBook Pro over WiFi (this is 5 minute stretches, because WiFi is so much noisier and because sending a 10MB sample over a 50Mb/s average WiFi takes a while):

![image](https://user-images.githubusercontent.com/16984005/83283002-c64b7d80-a1da-11ea-9d72-6ab555d39272.png)

and now:

![image](https://user-images.githubusercontent.com/16984005/83283017-cb103180-a1da-11ea-9e29-af509d876157.png)

So it really looks a lot better. The dip in 100B and 100kB throughput on WiFi in the "before" case could very well be WiFi related, but the horrors with 10MB samples are most certainly not a fluke.

**Comment by eboasson** [comment] 2020-05-30 13:45
Further to those failed builds on CI: it is caused by a small change in the default config, the increasing of the default upper limit for how much unacknowledged data is allowed (`WhcHigh` in the config). This causes the balance between the concurrent throughput measurement and round-trip counting in that sanity check to shift in favour of the former. It also seems quite logical: at 100kB max it should bump into the limit much more often than at 500kB, given the ping-ponging CPU time more often.

Naively one would say that there is no need for a context switch in the throughput publisher until it has published a number of samples that is proportional to the limit. So naively, one would expect a roughly linear relationship between that limit and the average interval between roundtrips (a.k.a. 1 / roundtrip count). I've tried it on my laptop:

![image](https://user-images.githubusercontent.com/16984005/83329957-893fc380-a28c-11ea-8d7a-9c4890953a4f.png)
(that's 1/roundtrip against said limit)

Combined with all the numbers roughly the same in the before & after cases when using the same limit settings and with CPU usage scaling along with it, I suppose that's convincing enough for me.

So now I must ponder what to do with that sanity check in the CI.

**Comment by clalancette** [comment] 2020-06-04 14:52
I was able to do some testing on the https://github.com/eboasson/cyclonedds/tree/rexmit-improvements branch this morning.  What I tested was the exact same setup as mentioned in the original description; namely, a triggered pipeline that causes two 640x480x3 images to be generated, which then is passed along to generate a final pointcloud of 9830400 bytes.

I tested a few different things:
1.  I set rmem_max to 30MB, and used the cyclone configuration file to request 20MB buffers (the original configuration above that I got to work well).  In this configuration, your new branch performs well, the same as before.
1.  I set rmem_max to 30MB, and did *not* use any cyclone configuration file.  This also works well, just about the same as above.
1.  I set rmem_max to 212992 (the default), and did *not* use any cyclone configuration file.  This continued to work very poorly, with it taking a very long time for the images to make it from one node to another, and the pointcloud taking a very long time (100s of seconds) to be published.
1.  After a bit of playing around, I set rmem_max to 851968, and did *not* use any cyclone configuration file.  This works well, with images and pointclouds being received regularly with an average pipeline latency of 141ms.

So overall, I'd say this is an improvement.  I would still love to see the third case above improved so that the out-of-the-box experience is better for users.

**Comment by eboasson** [comment] 2020-06-04 15:33
Thanks @clalancette!

> I would still love to see the third case above improved so that the out-of-the-box experience is better for users.

I totally agree. I am also somewhat surprised that it did so badly in that case — somewhat worse than with large buffers, sure, but not like this. It doesn't seem such a different scenario than the one I tried, but perhaps running only `ddsperf` affects the behaviour.

If only I knew how to do a packet capture using Wireshark while capturing only packets containing ACKNACK or HEARTBEAT ... (obviously you don't want those 10s of MBs!) Anyway, now that I know that behaviour is still there, it's worth another go at reproducing it.

**Comment by eboasson** [comment] 2020-06-12 13:25
Hi @clalancette, after thinking it through again, I realized that one thing bothered me about this whole affair (and other than the existence of the affair in the first place): 100s is a _very_ long time indeed and my measurements with master (see above) showed an absence of any significant network traffic, rather than the high network traffic you'd expect from the theory.

I think I may have found it. DDSI retransmits are driven by "heartbeat" message from the writer to the readers, informing them of data available for retransmit and (crucially) allowing them to request a retransmit. These are sent while there is unacknowledged data present, and in Cyclone, this occurs at a rate that drops after a while if no new samples have been written.

The argument behind reducing the rate is that if you're not sending new data and not getting any acknowledgements or retransmit requests, there's presumably something wrong and no-one is helped by sending more of these heartbeats. (And it works fine for smallish messages, it has been in use like this for almost a decade.)

However, in the case of very large messages, perhaps combined with a few lost packets and a bit of misfortune, it can lower the rate before the full sample has been received. Then, if ever the network drops a packet containing a heartbeat message needed to keep the request and reply cycles running smoothly while retrieving the remainder of the sample, you have to wait until the next scheduled heartbeat. If the rate goes down, that can be a while. If the rate never goes up until you write another sample, it can cause excessive delays.

For hand-waving numbers: Cyclone's default fragment size in master is 1.25kB, one can request up to 256 fragments at a time but Cyclone by default limits retransmit bursts to 50kB, and a 10MB sample requires 8k fragments. In short, worst-case, it requires some 200 round-trips. In practice it probably won't be that bad because a fair bit of the sample will make it through in the initial transmission. It turns out that under these circumstances the rate can drop to around 1Hz. And there you have a decent explanation for a 100s latency.

I have managed to catch this phenomenon in the master branch with wireshark. After changing the heartbeat scheduling to keep the rate up whenever retransmit requests of unacknowledged data are received, it no longer happens.

My rexmit-improvements branch contained no change that would have prevented the exact same misbehaviour. I have never seen it happen locally (despite trying) but it is all frightfully dependent on packet drops and timing and so it is quite possible that you ran into it and I didn't. I have added this small fix to that branch, along with some further refinements to the retransmit behaviour.

Would you be willing to give it another go? (Fingers crossed on my side, for two reasons: one that I have finally identified the root cause, and the other that the various bits of refactoring I did while looking for possible issues haven't broken anything. Needless to say, I am not asking you without having tried myself first!)

**Comment by clalancette** [comment] 2020-06-15 16:23
Hi @eboasson .

I got a chance to test out your new code today.  Just to be totally clear, I tested on commit https://github.com/eboasson/cyclonedds/commit/bff183cc3695a5758a768ca0fbc9387c501e1319 .  With that in place, I tested with rmem_max at 212992, and unfortunately I have to report that it is not working well.  Actually, in this case I ended up in the situation where the packets were *never* delivered (at least, I waited like 30 minutes and never saw them get delivered).  Looking a bit more closely there, it looks like the images were never delivered to the disparity node in the pipeline.  So I don't think the latest commits have improved the situation.

With other values for rmem_max (like 851968 and larger), it continues to work well.

**Comment by eboasson** [comment] 2020-06-15 18:50
Hi @clalancette, this is so strange. No matter what I try, it works fine — and I am trying crazy things: drop tons of packets (specifically also the first and the last), skip sending heartbeat messages that should be sent, deliberately not honoring retransmit requests, you name it. If 30 minutes in there is still something not delivered, there’s a close to 100% chance that I introduced an off-by-one error or suppressed a heartbeat message or a retransmit request too many. But where exactly? A rhetorical question ...  (And, by the way, I am positive none of those silly things I try made it into any of those commits.)

I presume you are running it on real hardware? So suppose I were to somehow find a regular PC of reasonably recent vintage, install Ubuntu 20.04 on it, load Foxy on it (in full) from the binary distribution, build `pc_pipe` and run the simulation (the mock up uses only 370kB large samples, so that can’t be what you are using), would that result in me running essentially the same as you?

When I tried in a VM I had a crashing gazebo, but perhaps that was also in part caused by my not installing all of Foxy. And in any case VMs tend to behave differently from real hardware, and I don’t want to waste time I don’t have.

**Comment by clalancette** [comment] 2020-06-15 21:17
> I presume you are running it on real hardware? So suppose I were to somehow find a regular PC of reasonably recent vintage, install Ubuntu 20.04 on it, load Foxy on it (in full) from the binary distribution, build `pc_pipe` and run the simulation (the mock up uses only 370kB large samples, so that can’t be what you are using), would that result in me running essentially the same as you?

Actually, I should back up a bit and explain my setup, because it is non-standard.

My host is a Fedora 31 x86_64, Intel Core i7-6800K, 32GB of RAM.  On that I have an Ubuntu *18.04* LXC container[1].  On that container, I compile all of [ROS 2 from source](https://index.ros.org/doc/ros2/Installation/Foxy/Linux-Development-Setup/#linux-latest), source it (source install/setup.bash) and then make an overlay and compile the repositories in the attached [pc_pipe.repos.log](https://github.com/eclipse-cyclonedds/cyclonedds/files/4782996/pc_pipe.repos.log).

Then I source the overlay, and launch the trigger system with:

```
RMW_IMPLEMENTATION=rmw_cyclonedds_cpp ros2 launch pc_pipe bringup.launch.xml viz:=true start_gazebo:=true
```

When that launches, that brings up both an RViz and Gazebo window.  I'll note that you *must* have Gazebo 9.13.1 from http://packages.osrfoundation.org/gazebo/ubuntu-stable installed, otherwise it will crash at the beginning.

Then finally, there is one more step, which is to run the [trigger_and_pointcloud.py.log](https://github.com/eclipse-cyclonedds/cyclonedds/files/4783018/trigger_and_pointcloud.py.log) script.  This script will subscribe to the pipeline, and then issue triggers to the pipeline.  Every time it gets a pointcloud, it triggers again.

I know that is fairly complicated, but its the setup that I know to reliably reproduce this.  Let me know if I can help you reproduce in other ways; for instance, I may be able to do set this up on real hardware on 20.04 and see how it does there.

[1] The customer that originally saw this problem is still on 18.04, and ROS 2 as of now still compiles there.  So I've kept to that setup.

**Comment by eboasson** [comment] 2020-06-16 15:12
@clalancette thank you very much for the explanation.

Regarding
> I tested on commit eboasson@bff183c 

I had to look into some completely unrelated issue and forgot to do it on another branch. The changes for the two activities are completely independent, so other that it being a bit annoying and confusing, it doesn't affect the experiment.

I am not going to try to replicate your setup exactly, but altogether it did allow me to finally get the "normal" version (so https://github.com/jacobperron/pc_pipe) running on Ubuntu 20.04 in VMWare on macOS. This after discovering your version is problematic for me because it depends on OpenCV 3 where I only have OpenCV 4. Some other details I managed to work around, such as changing the name space for the camera from "demo_cam" to "/". I also only get a ~5MB point cloud instead of ~10MB one, but that appears to not make a significant difference.

> Looking a bit more closely there, it looks like the images were never delivered to the disparity node in the pipeline. So I don't think the latest commits have improved the situation.

This is also what I found. I have been able to trace this back to the use of best-effort subscriptions (via `SensorDataQos`, e.g., in `DisparityNode::connectCb` and `PointCloudNode::connectCb`). A quick check in the sources that you referenced makes me think your version has the same problem.

This is particularly problematic for the images because those are already too large for my puny socket buffers, but it can even cause the camera_info to never arrive. I haven't fixed it; rather I have hacked around it by forcing everything to reliable in the RMW layer, that was easier for me.

With my hack in place, I dare say with Cyclone's master branch I observe qualitatively the same as you originally described:

![image](https://user-images.githubusercontent.com/16984005/84791333-bca38180-aff2-11ea-82ac-27b5b25d8655.png)

As you can see, latencies vary wildly and the maximum is almost 77s (not so different from roughly 100s). And a mere 515 point clouds over just over 11 minutes. My `rexmit-improvements` branch over roughly the same duration gives me:

![image](https://user-images.githubusercontent.com/16984005/84791355-c3ca8f80-aff2-11ea-84c6-6614d8c7b993.png)

So almost a 7-fold increase in point clouds and a much lower maximum, albeit still a bit higher than I'd like.

**Comment by clalancette** [comment] 2020-06-16 20:07
Ah, good point about the the best-effort.  I ended up doing the same hack as you (modifying both the DisparityNode and PointCloudNode to use SystemDefaultsQoS), and now things are working here, even with the default rmem_max of 212992.  That's some excellent work!

Thanks for going back and forth here.  From my perspective, it looks like this is vastly improved.  Let me know if you need me to do any more testing here.

**Comment by clalancette** [comment] 2020-07-06 18:20
@eboasson With #558 merged now, do you consider this issue resolved?  Should we close it?

**Comment by eboasson** [comment] 2020-07-06 21:00
Hi @clalancette, I think it is reasonable to consider it resolved. I am still puzzling a bit what exactly causes the 100ms “bumps” in the histogram, whether that is simply because of a base heartbeat interval of 100ms (the default, it can be changed) and the multiple stages in the pipeline giving opportunity for occasional packet loss in successive stages, adding retransmit intervals. If it isn’t that, I should still have some room for improvement 😀.

But the extremely long latencies have been solved, and the over-eager retransmit handling (which turned out to be a second-order effect for this) has been much improved. I am not saying “solved” because it is (still) somewhat bit dependent on actual network timing: if the “NACK delay” setting is shorter than the network roundtrip plus the latency incurred by performing the retransmits, there is still some of it — which is visible in the WiFi graphs in #558 with 10MB samples.

So yes, let’s close it. If something similar pops up again, just make a new one!

**Closed by eboasson** 2020-07-06 21:00 UTC

**Comment by wjwwood** [comment] 2022-09-08 22:52
@clalancette  Should the docs referencing this be updated? https://docs.ros.org/en/rolling/How-To-Guides/DDS-tuning.html#cyclone-dds-tuning

**Comment by eboasson** [comment] 2022-09-09 07:13
@wjwwood in my opinion it would make sense to update it, but I wouldn't keep the general advice to have a socket receive buffer large enough to hold the data. It does behave quite nicely even with the default settings, but if you have a small socket buffer and large samples, there is a fair likelihood of packet loss and that does result in a higher network load and longer latency.

**Comment by swiz23** [comment] 2023-03-22 22:43
@eboasson,

> This is also what I found. I have been able to trace this back to the use of best-effort subscriptions (via SensorDataQos, e.g., in DisparityNode::connectCb and PointCloudNode::connectCb). A quick check in the sources that you referenced makes me think your version has the same problem.

> This is particularly problematic for the images because those are already too large for my puny socket buffers, but it can even cause the camera_info to never arrive. I haven't fixed it; rather I have hacked around it by forcing everything to reliable in the RMW layer, that was easier for me.

I realize this issue has been closed for a while, but I just wanted to clarify something. You mentioned that you were able to significantly decrease the max latency by changing the QoS settings of the DisparityNode::connectCb and PointCloudNode::connectCb callbacks from SensorDataQoS to SystemDefaultQos. By making this change, I assume this makes these subscribers have the same QoS profile as the publishers that are publishing data to them.

My question is why does having a SensorDataQoS profile for the subscribers cause this latency? Isn't it a good design from a QoS standpoint to have a ros2 node publishing sensor data 'reliably' and a subscriber getting that data using 'best effort'?

And what is the relationship between these profiles and the rmem_max socket buffer?

**Comment by eboasson** [comment] 2023-03-23 13:20
@swiz23 that's a blast from the past 🙂 I do have a pretty decent memory, but I don't remember why switching from best-effort to reliable decreased the latency and it was a fairly complex setup. That said, there are some ways of determining the latency that could yield large numbers if some data is lost, so I am assuming it could have been something like that. If there is a good reason to dig deeper and verify this assumption, then so be it, but I am not going there immediately.

Under this assumption, the problem really is simply message loss, caused by the use of best-effort.

> Isn't it a good design from a QoS standpoint to have a ros2 node publishing sensor data 'reliably' and a subscriber getting that data using 'best effort'?

I'd say no, not for large messages. In DDS, a reader must receive all message fragments — with a single fragment possibly split over multiple packets — to make the message available to the reader. A reliable reader, can request a retransmit of a lost fragment, but a best-effort reader must receive all packets to reconstruct the message, and so for a best-effort reader a single lost packet means the entire message is dropped.

With point clouds of several MBs — if I am not mistaken, 15MB is not implausible and makes the math easy — then on Ethernet you'd have about 1.5kB per packet, and a single point cloud turns into 10k packets. Any single one of them lost means a best-effort reader drops it. On a loopback interface, it is more likely (order-of-magnitude) 60kB per packet, and so 250 packets or so.

Packet loss typically occurs when a buffer is full on the receiving end because it seems that with modern hardware packet loss due to noise on the line is negligible. Switches generally can handle crazy rates, especially for unicast, so you typically get packet loss when:
* multiple huge data streams are converging on a single outgoing port in a switch (all people I know that have had to deal with such limits were very much aware of them and designed the system to avoid this particular problem),
* you have so many fragmented IP messages that the kernel buffer space for re-assembly is exhausted (I forget what the setting for this buffer size is, but this is trivially solved by raising the size),
* the application software processing the packets can't quite keep up and the kernel's network processing runs into a full UDP receive buffer.

The last one is therefore the first one to check. If that UDP receive buffer is large enough to hold a full message (plus a bit) and the DDS receive code can keep up on average, then generally at least every other message (or so, forgive the hand-waving) can be buffered in full by the kernel is certain to arrive. That allows for a lot of scheduling latencies and whatnot. If it is smaller, or, obviously, if it really can't keep up, then it is possible not a single large message is received in its entirety.

And then you have some vagaries ... processing incoming fragments and checking whether the message has been in received in full is pretty cheap. But once it is complete, it needs to undergo further processing, be handed off to the reader history cache, and it needs to be copied from the reader history cache to the application. (Loans help with the latter.) Somewhere along the process it needs to be deserialised as well. All these steps take time, and that can mean not pulling packets from the UDP receive buffer for a short period.

At the data rates you're talking about over loopback or 100GbE, that receive buffer fills up rather quickly (6GB/s or so on my laptop) and a mere 100µs additional latency can be a problem already: 600kB is already significantly above the default maximum of (most?) Linux kernels. That 100µs is not a random number, it is only a bit higher than the time it takes for a modern CPU to wake up from a low-power state, the type it enters when it spends a ms or so in an idle loop. So on a quiet machine, with default kernel limits in Linux and a 100GbE, you'd almost expect packet loss when a remote node suddenly starts sending a point cloud!

Given that *that* is roughly how the numbers work out, you really need to make sure to avoid packet loss at (nearly all cost) if using best-effort for large messages. Most people that select "sensor QoS" never do this bit of back-of-the-envelope math and would IMHO be better of if "reliable" were always used as the default, at least when large messages are used (it could even be large data pushing out small samples!)

> And what is the relationship between these profiles and the rmem_max socket buffer?

Raising `rmem_max` (and actually using it, in Cyclone via the `SocketReceiveBufferSize` option) for best-effort is essentially a must in my view. For reliable communication it is not as important because the effective throughput tends to drop somewhat gracefully, but it does go down significantly, latency goes up and the retransmits take CPU and network bandwidth.

**Comment by swiz23** [comment] 2023-04-05 22:34
Thanks for that really detailed answer!! I really appreciate it.

**Comment by Seangottarun** [comment] 2023-04-05 22:43
@eboasson I recently came across the cyclone dds tuning guidelines when debugging dropped messages with `rclcpp::SensorDataQoS()` with ROS 2 Humble and cyclone dds. I'm trying to figure out

1. How do I determine the `rmem_max` value with the best tradeoffs?
2. Should I actually be using a reliable QoS?

https://docs.ros.org/en/humble/How-To-Guides/DDS-tuning.html#cyclone-dds-tuning

For my use case, I have 4 separate topics each with a 5 MB `sensor_msgs/Image` message that is sent at 16 Hz. When I just run `ros2 topic hz <topic>` I see ~16 Hz. The topic rate drops to 2 Hz when I run another node subscribed to the topic, but with cyclone dds tuning example for a 9 MB message, I can get the expected ~16 Hz.
