### ISSUE TITLE
The problem with transmitting big data

### ISSUE THREAD

**Issue by jwcesign** [eclipse-cyclonedds/cyclonedds#168] opened 2019-04-29 03:31 UTC
Hi, I want to use dds to transmit big data message with 50ms period. But the result is: the pub will take more and more memory with time going. The code is here;
~~~c
#include "ddsc/dds.h"
#include "HelloWorldData.h"
#include <stdio.h>
#include <stdlib.h>

int main(int argc, char **argv) {
  dds_entity_t participant;
  dds_entity_t topic;
  dds_entity_t writer;
  dds_return_t ret;
  HelloWorldData_Msg msg;
  dds_listener_t *listener = NULL;
  (void) argc;
  (void) argv;

  /* Create a Participant. */
  participant = dds_create_participant(33, NULL, NULL);

  /* Create a Topic. */
  topic = dds_create_topic(participant, &HelloWorldData_Msg_desc,"HelloWorldData_Msg", NULL, NULL);

  /* Create a Writer. */
  dds_qos_t *writer_qos = dds_create_qos();
  dds_qset_reliability(writer_qos, DDS_RELIABILITY_RELIABLE, DDS_INFINITY);
  dds_qset_history(writer_qos, DDS_HISTORY_KEEP_ALL, 0);//DDS_KEEP_LAST_HISTORY_QOS
  writer = dds_create_writer(participant, topic, writer_qos, listener);
  printf("=== [Publisher]  Waiting for a reader to be discovered ...\n");

  ret = dds_set_status_mask(writer, DDS_PUBLICATION_MATCHED_STATUS);

  /* Create a message to write. */
  char *data = (char *)malloc(3000000);//3000000
  memset(data, 'a', 3000000);
  msg.userID = 1;
  msg.message = data;

  printf("=== [Publisher]  Writing : ");
  printf("Message (%d)\n", msg.userID);

  ret = dds_write(writer, &msg);
  //dds_sleepfor(DDS_SECS (7));
  for (int i = 1; i < 3000000; i++)
  {
    msg.userID = i;
    printf("Message (%d)\n", msg.userID);
    ret = dds_write(writer, &msg);
    dds_sleepfor(DDS_MSECS (50));
  }

  /* Deleting the participant will delete all its children recursively as well. */
  ret = dds_delete(participant);

  return EXIT_SUCCESS;
}
~~~

~~~c
#include "ddsc/dds.h"
#include "HelloWorldData.h"
#include <stdio.h>
#include <string.h>
#include <stdlib.h>

/* An array of one message (aka sample in dds terms) will be used. */
#define MAX_SAMPLES 1

static void data_available(dds_entity_t rd, void *arg)
{
  int status, samplecount;
  void *samples[MAX_SAMPLES];
  dds_sample_info_t infos[MAX_SAMPLES];
  HelloWorldData_Msg *msg;
  samples[0] = HelloWorldData_Msg__alloc ();
  samplecount = dds_take (rd, samples, infos, MAX_SAMPLES, MAX_SAMPLES);
  if ((samplecount > 0) && (infos[0].valid_data))
  {
    /* Print Message. */
    msg = (HelloWorldData_Msg*) samples[0];
    printf ("=== [Subscriber] Received : ");
    printf ("Message (%d)\n", msg->userID);
  }
  HelloWorldData_Msg_free (samples[0], DDS_FREE_ALL);
}

int main (int argc, char ** argv)
{
    dds_entity_t participant;
    dds_entity_t topic;
    dds_entity_t reader;
    dds_return_t ret;
    dds_qos_t *qos;
    dds_listener_t *listener = NULL;
    int flag = 0;
    (void)argc;
    (void)argv;

    /* Create a Participant. */
    participant = dds_create_participant (33, NULL, NULL);

    /* Create a Topic. */
    topic = dds_create_topic (participant, &HelloWorldData_Msg_desc,
                              "HelloWorldData_Msg", NULL, NULL);

    /* Create a reliable Reader. */
    qos = dds_qos_create ();
    dds_qset_reliability(qos, DDS_RELIABILITY_RELIABLE, DDS_INFINITY);
    dds_qset_history(qos, DDS_HISTORY_KEEP_ALL, 0);
    listener = dds_listener_create(NULL);
    dds_lset_data_available(listener, data_available);
    reader = dds_create_reader (participant, topic, qos, listener);
    dds_qos_delete(qos);

    printf ("\n=== [Subscriber] Waiting for a sample ...\n");

    /* Initialize sample buffer, by pointing the void pointer within
     * the buffer array to a valid sample memory location. */
    //samples[0] = HelloWorldData_Msg__alloc ();

    /* Poll until data has been read. */
    // while (true)
    // {
    //     /* Do the actual read.
    //      * The return value contains the number of read samples. */
    //     ret = dds_take (reader, samples, infos, MAX_SAMPLES, MAX_SAMPLES);
    //     DDS_ERR_CHECK (ret, DDS_CHECK_REPORT | DDS_CHECK_EXIT);

    //     /* Check if we read some data and it is valid. */
    //     
    //     else
    //     {
    //         /* Polling sleep. */
    //         dds_sleepfor (DDS_MSECS (2));
    //     }
    // }

    while (true) {
        dds_sleepfor (DDS_MSECS (2));
    }

    /* Free the data location. */
    //HelloWorldData_Msg_free (samples[0], DDS_FREE_ALL);

    /* Deleting the participant will delete all its children recursively as well. */
    ret = dds_delete (participant);

    return EXIT_SUCCESS;
}
~~~

And the pub takes too much memory as follows:
~~~
   PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND        
214456 root      20   0  633988 274932   4048 S  13.3  6.9   0:52.64 big_data_pub                  
214448 root      20   0  300252  25340   3704 R  12.0  0.6   0:47.23 big_data_sub  
~~~

With time going, `RES` gets bigger and bigger .

**Comment by jwcesign** [comment] 2019-04-30 01:23
By the way, the sub received all the data, so the writer will delete all the acked message

**Comment by eboasson** [comment] 2019-04-30 15:28
Hi @jwcesign ,

I'm quite sure the problem is an old quick experiment for caching some really oft-used data structures (samples, messages and WHC nodes) gone rogue. Caching these does make some sense for high-throughput small samples, but it has no advantage for large samples in general and apparently can cause memory use to blow up even though there is hardly any live data. (There isn't here: the samples get acknowledged promptly, so you'd expect two or so samples while things are flowing smoothly.)

As an aside, assuming you are using an unmodified ``HelloWorldData.idl`` there is also a small but real leak in your test: the ``userID`` field is a key and DDS will keep track of some data for each key value if you don't unregister it. That amounts to some administrative stuff and a key value, so it's nothing like what you see disappear in those caches.

Disabling the caching is pretty simple, you might want to give the patch below a try. I will certainly fix it soonish because such memory usage is unacceptable, but I don't want to lose my nice performance numbers just yet ... I'd like to first see if I can keep some caching where it makes sense while also limiting the amount of memory they occupy.

```patch
diff --git a/src/core/ddsi/include/dds/ddsi/q_freelist.h b/src/core/ddsi/include/dds/ddsi/q_freelist.h
index 8fcafa7..e4e58b2 100644
--- a/src/core/ddsi/include/dds/ddsi/q_freelist.h
+++ b/src/core/ddsi/include/dds/ddsi/q_freelist.h
@@ -19,11 +19,11 @@
 extern "C" {
 #endif
 
-#define FREELIST_SIMPLE 1
+#define FREELIST_NONE 1
 #define FREELIST_ATOMIC_LIFO 2
 #define FREELIST_DOUBLE 3
 
-#define FREELIST_TYPE FREELIST_DOUBLE
+#define FREELIST_TYPE FREELIST_NONE
 
 #if 0
 #if HAVE_ATOMIC_LIFO
@@ -33,7 +33,13 @@ extern "C" {
 #endif
 #endif
 
-#if FREELIST_TYPE == FREELIST_ATOMIC_LIFO
+#if FREELIST_TYPE == FREELIST_NONE
+
+struct nn_freelist {
+  char dummy;
+};
+
+#elif FREELIST_TYPE == FREELIST_ATOMIC_LIFO
 
 struct nn_freelist {
   ddsrt_atomic_lifo_t x;
diff --git a/src/core/ddsi/src/q_freelist.c b/src/core/ddsi/src/q_freelist.c
index 78e2a77..b609190 100644
--- a/src/core/ddsi/src/q_freelist.c
+++ b/src/core/ddsi/src/q_freelist.c
@@ -18,7 +18,32 @@
 #include "dds/ddsrt/threads.h"
 #include "dds/ddsi/q_freelist.h"
 
-#if FREELIST_TYPE == FREELIST_ATOMIC_LIFO
+#if FREELIST_TYPE == FREELIST_NONE
+
+void nn_freelist_init (struct nn_freelist *fl, uint32_t max, off_t linkoff)
+{
+}
+
+void nn_freelist_fini (struct nn_freelist *fl, void (*free) (void *elem))
+{
+}
+
+bool nn_freelist_push (struct nn_freelist *fl, void *elem)
+{
+  return false;
+}
+
+void *nn_freelist_pushmany (struct nn_freelist *fl, void *first, void *last, uint32_t n)
+{
+  return first;
+}
+
+void *nn_freelist_pop (struct nn_freelist *fl)
+{
+  return NULL;
+}
+
+#elif FREELIST_TYPE == FREELIST_ATOMIC_LIFO
 
 void nn_freelist_init (struct nn_freelist *fl, uint32_t max, off_t linkoff)
 {
```

**Comment by jwcesign** [comment] 2019-05-05 10:32
Thanks a lot, I will try the patch.

**Comment by eboasson** [comment] 2019-05-31 05:54
@jwcesign , I assume you don't mind my closing this issue given that I merged a fix (the workaround I mentioned is in there as a compile-time option, though it requires modifying the source).

**Closed by eboasson** 2019-05-31 05:54 UTC
