### ISSUE TITLE
Failed to build ddsperf

### ISSUE THREAD

**Issue by YuanYuYuan** [eclipse-cyclonedds/cyclonedds#1525] opened 2022-12-21 05:39 UTC
Hi, I failed to compile ddsperf after the commit 2d906b0d7516621fba07d97adb8ca4166f9fd481.

* To reproduce
```
cmake -Bbuild -DCMAKE_BUILD_TYPE=Release
cmake --build build --config Release -j
```

* Error log
```text
[ 98%] Generating ddsperf_types.c, ddsperf_types.h
../../../bin/idlc: symbol lookup error: ../../../bin/idlc: undefined symbol: DDS_XTypes_TypeMapping_cdrstream_desc
make[2]: *** [src/tools/ddsperf/CMakeFiles/ddsperf_types_generate.dir/build.make:75: src/tools/ddsperf/ddsperf_types.c] Error 127
make[1]: *** [CMakeFiles/Makefile2:505: src/tools/ddsperf/CMakeFiles/ddsperf_types_generate.dir/all] Error 2
make: *** [Makefile:156: all] Error 2
```

Can someone give some clues to fix it?

**Comment by YuanYuYuan** [comment] 2022-12-21 07:14
[Update] I found that the problem is I had an old CycloneDDS installed under ~/.local. So don't worry about this issue. Sorry for the interruption.

**Comment by eboasson** [comment] 2022-12-21 07:35
No worries and thanks for the update ☺️

**Comment by kjrusscher** [comment] 2023-02-21 20:33
I keep running into this problem with the 0.10.x versions. I can build the 0.9.1 version. I've removed all *cyclone*, *dds* and idlc stuff from /usr and /home (as far as I know). Does anyone have any idea how to solve this?

**Comment by eboasson** [comment] 2023-02-22 08:09
Strange, if I were to run into this myself and found myself at wits end, I would:
1. try reproducing the error by running `idlc` manually (which is straightforward)
2. run `ldd` on it (or use `LD_TRACE_LOADED_OBJECTS` — see https://man7.org/linux/man-pages/man8/ld.so.8.html))
3. possibly do `LD_LIBRARY_PATH= <build_dir>/lib <build_dir>/bin/idlc ...`
4. then move on to `LD_DEBUG=files, libs LD_DEBUG_OUTPUT=somefile.txt .../bin/idlc ...`

and if then I can't find it, I go for a walk in the woods or snooze in the sunshine and start over at 1 ...

I know this is pretty much standard advice and that it is not necessarily all that helpful for me to write it out here. But perhaps it triggers some idea, or you perhaps try something of the sort, share the output and then we figure it out.

**Comment by kjrusscher** [comment] 2023-02-22 09:01
The problem was cause by also having ROS2 Galactic installed. Removing ROS2 Galatic solved the problem.

**Comment by eboasson** [comment] 2023-02-22 09:04
Ah, ok! Thanks for the update. Then I'll close the issue again.

**Closed by eboasson** 2023-02-22 09:04 UTC
